# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: moubah.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmoubah.proto\x1a\x1bgoogle/protobuf/empty.proto\"P\n\x0c\x41udioRequest\x12\x12\n\ninput_path\x18\x01 \x01(\t\x12\x13\n\x0boutput_path\x18\x02 \x01(\t\x12\x17\n\x0fremove_original\x18\x03 \x01(\x08\"\x15\n\x07Process\x12\n\n\x02id\x18\x01 \x01(\x05\"3\n\x0fGenericResponse\x12\x11\n\tsucceeded\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xa0\x01\n\x0cMusicRemover\x12.\n\nGetProcess\x12\x16.google.protobuf.Empty\x1a\x08.Process\x12\x30\n\x04Ping\x12\x16.google.protobuf.Empty\x1a\x10.GenericResponse\x12.\n\x0bRemoveMusic\x12\r.AudioRequest\x1a\x10.GenericResponseb\x06proto3')



_AUDIOREQUEST = DESCRIPTOR.message_types_by_name['AudioRequest']
_PROCESS = DESCRIPTOR.message_types_by_name['Process']
_GENERICRESPONSE = DESCRIPTOR.message_types_by_name['GenericResponse']
AudioRequest = _reflection.GeneratedProtocolMessageType('AudioRequest', (_message.Message,), {
  'DESCRIPTOR' : _AUDIOREQUEST,
  '__module__' : 'moubah_pb2'
  # @@protoc_insertion_point(class_scope:AudioRequest)
  })
_sym_db.RegisterMessage(AudioRequest)

Process = _reflection.GeneratedProtocolMessageType('Process', (_message.Message,), {
  'DESCRIPTOR' : _PROCESS,
  '__module__' : 'moubah_pb2'
  # @@protoc_insertion_point(class_scope:Process)
  })
_sym_db.RegisterMessage(Process)

GenericResponse = _reflection.GeneratedProtocolMessageType('GenericResponse', (_message.Message,), {
  'DESCRIPTOR' : _GENERICRESPONSE,
  '__module__' : 'moubah_pb2'
  # @@protoc_insertion_point(class_scope:GenericResponse)
  })
_sym_db.RegisterMessage(GenericResponse)

_MUSICREMOVER = DESCRIPTOR.services_by_name['MusicRemover']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUDIOREQUEST._serialized_start=45
  _AUDIOREQUEST._serialized_end=125
  _PROCESS._serialized_start=127
  _PROCESS._serialized_end=148
  _GENERICRESPONSE._serialized_start=150
  _GENERICRESPONSE._serialized_end=201
  _MUSICREMOVER._serialized_start=204
  _MUSICREMOVER._serialized_end=364
# @@protoc_insertion_point(module_scope)
